return {

	-- -- cmdline tools and lsp servers
	-- {
	-- 	"williamboman/mason.nvim",
	-- 	cmd = "Mason",
	-- 	keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
	-- 	opts = {
	-- 		ensure_installed = {
	-- 			"stylua",
	-- 			"shellcheck",
	-- 			"shfmt",
	-- 			"flake8",
	-- 			"eslint_d",
	-- 		},
	-- 	},
	-- 	---@param opts MasonSettings | {ensure_installed: string[]}
	-- 	config = function(_, opts)
	-- 		require("mason").setup(opts)
	-- 		local mr = require("mason-registry")
	-- 		for _, tool in ipairs(opts.ensure_installed) do
	-- 			local p = mr.get_package(tool)
	-- 			if not p:is_installed() then
	-- 				p:install()
	-- 			end
	-- 		end
	-- 	end,
	-- },

	-- {
	-- 	"glepnir/lspsaga.nvim",
	-- 	event = "BufRead",
	-- 	config = function()
	-- 		require("lspsaga").setup({
	-- 			lightbulb = {
	-- 				enable = false,
	-- 			},
	-- 			code_action = {
	-- 				show_server_name = true,
	-- 				extend_gitsigns = true,
	-- 			},
	-- 			rename = {
	-- 				quit = "q",
	-- 			},
	-- 			ui = {
	-- 				title = false,
	-- 			},
	-- 			symbol_in_winbar = {
	-- 				enable = false,
	-- 			},
	-- 		})
	-- 	end,
	-- 	dependencies = {
	-- 		{ "nvim-tree/nvim-web-devicons" },
	-- 		--Please make sure you install markdown and markdown_inline parser
	-- 		{ "nvim-treesitter/nvim-treesitter" },
	-- 	},
	-- },
}
