return {
  -- Replaces text-input and select UI elements
  -- TODO: Consider removing after renoving inc-rename, what do I still need this for?
  -- Does seems like it can replace lsp saga rename
  -- {
  --   "stevearc/dressing.nvim",
  --   opts = {
  --     -- NOTE: Has a lot of configuration options
  --
  --     input = {
  --       insert_only = false,
  --       start_in_insert = false,
  --       -- Default mappings
  --       mappings = {
  --         n = {
  --           ["<Esc>"] = "Close",
  --           ["<CR>"] = "Confirm",
  --         },
  --         i = {
  --           ["<C-c>"] = "Close",
  --           ["<CR>"] = "Confirm",
  --           ["<Up>"] = "HistoryPrev",
  --           ["<Down>"] = "HistoryNext",
  --         },
  --       },
  --     },
  --   },
  -- },
}
